name: main

on: [push]

jobs:
  build-infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          if [-f requirements.txt]; then pip install -r requirements.txt; fi
      - name: test get_function
        run: cd tests/unit/ && python -m pytest tests/unit/test_handler.py